---
- hosts: cluster_nodes
  become: yes
  become_user: root
  tasks:
  - name: Create Volume Group
    lvg:
      vg: coucbase-data-vg01
      pvs: /dev/sdb
  - name: Create Logical Volume
    lvol:
      vg: coucbase-data-vg01
      lv: data-lv01
      size: 100%FREE
      shrink: false
  - name: Add Data Filesystem
    filesystem:
      fstype: xfs
      dev: /dev/coucbase-data-vg01/data-lv01
  - name: Mount Data Filesystem
    mount:
      name: /var/lib/couchbase
      src: /dev/coucbase-data-vg01/data-lv01
      fstype: xfs
      opts: rw
      state: mounted
